### Register a User
POST http://localhost:3000/register
Content-Type: application/x-www-form-urlencoded

username=testuser&password=TestPass123&key=MyRegKey

### Login a User
POST http://localhost:3000/login
Content-Type: application/x-www-form-urlencoded

username=testuser&password=TestPass123
